package com.insurance.claimservice.model;

import javax.persistence.*;
import java.time.LocalDate;


/*
Add appropriate annotation/s to map the class and its properties with a Database entity
    - claimId should be unique and generated by the Database
    - table name should be insurance_claims
 */
@Entity
@Table(name = "insurance_claims")
public class Claim {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer claimId;
    private String policyId;
    private String hospitalId;
    private LocalDate claimDate;
    private String status;
    private double amountClaimed;

    public Claim() {
    }

    public Claim(Integer claimId, String policyId, String hospitalId, LocalDate claimDate, String status, double amountClaimed) {
        this.claimId = claimId;
        this.policyId = policyId;
        this.hospitalId = hospitalId;
        this.claimDate = claimDate;
        this.status = status;
        this.amountClaimed = amountClaimed;
    }

    public Integer getClaimId() {
        return claimId;
    }

    public void setClaimId(Integer claimId) {
        this.claimId = claimId;
    }

    public String getPolicyId() {
        return policyId;
    }

    public void setPolicyId(String policyId) {
        this.policyId = policyId;
    }

    public String getHospitalId() {
        return hospitalId;
    }

    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }

    public LocalDate getClaimDate() {
        return claimDate;
    }

    public void setClaimDate(LocalDate claimDate) {
        this.claimDate = claimDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public double getAmountClaimed() {
        return amountClaimed;
    }

    public void setAmountClaimed(double amountClaimed) {
        this.amountClaimed = amountClaimed;
    }
}
